## Configure G4SBS for gmn (Q^2 = 3 GeV^2)
/g4sbs/filename        gmn_3GeV2.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             gmn

## Configure the target
/g4sbs/target          LD2
/g4sbs/targlen         15.0 cm           ## Target Length
/g4sbs/rasterx 	       2.0 mm  #raster size in X
/g4sbs/rastery	       2.0 mm  #raster size in Y

## Configure generator settings
/g4sbs/kine            gun           ## Generator
/g4sbs/particle	       proton
/g4sbs/gunpol	       1 0 0
/g4sbs/runtime         1.0 s
/g4sbs/beamcur         30.0 muA
/g4sbs/beamE           3.7283 GeV
/g4sbs/thmin           31.9 deg
/g4sbs/thmax           31.9 deg
/g4sbs/phmin           180 deg
/g4sbs/phmax           180 deg

## Configure standard detector settings
/g4sbs/hcaldist        11.0 m
/g4sbs/hcalvoffset     0.45 m
/g4sbs/beamlineconfig  4                 ## set relevant beamline configuration
/g4sbs/sbsclampopt     3                 ## Front field clamp only

## Configure the magnets
/g4sbs/bbfield         1
/g4sbs/scalebbfield    0.9672
#/g4sbs/tosfield        GMN13_field_newheader.table
/g4sbs/sbsmagfield     0. tesla
/g4sbs/48d48field      1
/g4sbs/bbang           36.0 deg
/g4sbs/bbdist          1.80 m
/g4sbs/sbsang          31.9 deg
/g4sbs/48D48dist       2.25 m 


/g4sbs/keepsdtrackinfo 	all true
/g4sbs/totalabs true

## Run 100 events
#/g4sbs/run             10000

/g4sbs/uselead 	     0

#visualization stuff:
# Use this open statement to create an OpenGL view:
/vis/open OGLI 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 89 deg
#
# Specify zoom value:
/vis/viewer/zoom 2.5
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings



#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  1
#/vis/geometry/set/visibility RICHbox_log -1 0

/vis/geometry/set/forceWireframe b48d48Log -1 1
/vis/geometry/set/forceWireframe FrontClamp_log -1 1

/vis/viewer/flush
